import { build } from 'esbuild';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const sql=new DatabaseSync(':memory:');sql.exec('PRAGMA foreign_keys=ON');sql.exec(readFileSync('drizzle/0000_uneven_obadiah_stane.sql','utf8'));
function prepared(query){let args=[];return {bind(...values){args=values;return this},async first(){return sql.prepare(query).get(...args)??null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){const r=sql.prepare(query).run(...args);return {meta:{changes:Number(r.changes)}}}}}
globalThis.__testDB={prepare:prepared,async batch(items){sql.exec('BEGIN');try{const r=[];for(const i of items)r.push(await i.run());sql.exec('COMMIT');return r}catch(e){sql.exec('ROLLBACK');throw e}}};
globalThis.__testUser=null;
await build({entryPoints:['app/api/board/route.ts'],outfile:'.sites-runtime/test-route.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'test-runtime',setup(b){b.onResolve({filter:/^cloudflare:workers$/},()=>({path:'env',namespace:'test'}));b.onResolve({filter:/chatgpt-auth$/},()=>({path:'auth',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='env'?"export const env={DB:globalThis.__testDB,SITE_OWNER_EMAIL:'owner@example.test'}":"export async function getChatGPTUser(){return globalThis.__testUser}"}))}}]});
const {GET,POST}=await import('../.sites-runtime/test-route.mjs');
const user=(email,id=email)=>{globalThis.__testUser={userId:id,email,displayName:email}};
async function post(data,origin='https://en.example'){const r=await POST(new Request('https://en.example/api/board',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(data)}));return {status:r.status,data:await r.json()}}
let r=await GET();assert.equal(r.status,200);let b=await r.json();assert.equal(b.clips.length,52);assert.equal(b.user,null);
assert.equal((await post({action:'vote',id:'gol-1'})).status,401);
user('member@example.test');assert.equal((await post({action:'editor',email:'hacker@example.test',add:true})).status,403);
assert.equal((await post({action:'design',design:b.design,version:1})).status,403);
assert.equal((await post({action:'clip',id:'gol-1'})).status,403);
assert.equal((await post({action:'vote',id:'gol-1'},'https://other.example')).status,403);
assert.equal((await post({action:'vote',id:'gol-1'})).status,200);
assert.equal((await post({action:'vote',id:'gol-2'})).status,409);
assert.equal((await post({action:'vote',id:'serbest-1'})).status,200);
assert.equal((await post({action:'vote',id:'kart-13'})).status,409);
user('owner@example.test');assert.equal((await post({action:'editor',email:'editor@example.test',add:true})).status,200);
r=await GET();b=await r.json();assert.equal(b.user.role,'owner');
assert.equal((await post({action:'design',design:{...b.design,title:'Test başlık'},version:b.version})).status,200);
assert.equal((await post({action:'design',design:b.design,version:b.version})).status,409);
user('editor@example.test');r=await GET();b=await r.json();assert.equal(b.user.role,'editor');
assert.equal((await post({action:'design',design:b.design,version:b.version})).status,403);
assert.equal((await post({action:'editor',email:'new@example.test',add:true})).status,403);
const voted=b.clips.find(c=>c.id==='gol-1');
assert.equal((await post({action:'clip',id:voted.id,title:'Yeni başlık',url:'https://youtu.be/abcdefghijk',previousEmbed:voted.embed})).status,409);
assert.equal((await post({action:'clip',id:voted.id,title:'Yeni başlık',url:voted.embed,previousEmbed:voted.embed})).status,200);
assert.equal((await post({action:'clip',id:'kart-13',title:'Video eklendi',url:'https://youtu.be/abcdefghijk',previousEmbed:''})).status,200);
assert.equal((await post({action:'clip',id:'kart-12',title:'Hatalı kaynak',url:'https://evil.test/embed/anything',previousEmbed:''})).status,400);
user('owner@example.test');assert.equal((await post({action:'editor',email:'editor@example.test',add:false})).status,200);
user('editor@example.test');assert.equal((await post({action:'clip',id:'kart-12'})).status,403);
user('owner@example.test');b=await (await GET()).json();
assert.equal(b.design.editor.home.ballSize,280);
const nextDesign=structuredClone(b.design);nextDesign.editor.home.font='serif';nextDesign.editor.home.ballSize=320;nextDesign.editor.rooms.gol={background:'#123456',championWidth:780,elements:{title:{fontSize:44,italic:true}}};
assert.equal((await post({action:'design',design:nextDesign,version:b.version})).status,200);
b=await (await GET()).json();assert.equal(b.design.editor.home.font,'serif');assert.equal(b.design.editor.home.ballSize,320);assert.equal(b.design.editor.rooms.gol.championWidth,780);assert.equal(b.design.editor.rooms.gol.elements.title.italic,true);assert.equal(b.design.editor.rooms.faul,undefined);
const invalid=structuredClone(b.design);invalid.editor.home.elements={'body':{fontSize:40}};assert.equal((await post({action:'design',design:invalid,version:b.version})).status,400);
invalid.editor.home.elements={};invalid.editor.home.backgroundImage='javascript:alert(1)';assert.equal((await post({action:'design',design:invalid,version:b.version})).status,400);
user('member@example.test');assert.equal((await post({action:'design',design:b.design,version:b.version})).status,403);
console.log('PASS: old designs receive defaults; owner appearance round-trip; home/room isolation; safe object keys and image URLs; members cannot save design.');
console.log('PASS: 52 slots, sign-in, role permissions, cross-origin rejection, one vote per room, empty slot, owner settings, version conflict, editor grants/revocation, voted video protection, safe video URLs.');sql.close();
