'use client';
import {useState} from 'react';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {elementMap,fonts,pageSchema,labelDefaults,type PageAppearance,type ElementKey,type ObjectAppearance} from '@/lib/appearance';
import type {Design} from '@/lib/catalog';
export function Choice({value,options,onChange}:{value:string;options:[string,string][];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Range({label,value,min,max,step=1,onChange}:{label:string;value:number;min:number;max:number;step?:number;onChange:(n:number)=>void}){return <label>{label}<div className="range-row"><Slider aria-label={label} min={min} max={max} step={step} value={[value]} onValueChange={v=>onChange(v[0])}/><output>{value}</output></div></label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="switch-label">{label}<Switch checked={value} onCheckedChange={onChange}/></label>}
export default function DesignPanel({open,setOpen,draft,setDraft,room,save,discard,busy,dirty}:{open:boolean;setOpen:(v:boolean)=>void;draft:Design;setDraft:(d:Design)=>void;room?:string;save:()=>void;discard:()=>void;busy:boolean;dirty:boolean}){
 const [element,setElement]=useState<ElementKey>('title');const page=room?draft.editor.rooms[room as keyof typeof draft.editor.rooms]??pageSchema.parse({}):draft.editor.home;
 function setPage(next:PageAppearance){setDraft({...draft,editor:room?{...draft.editor,rooms:{...draft.editor.rooms,[room]:next}}:{...draft.editor,home:next}})}
 const update=(key:string,value:unknown)=>setPage({...page,[key]:value});const object=page.elements[element]??{};
 function setObject(key:string,value:unknown){setPage({...page,elements:{...page.elements,[element]:{...object,[key]:value}}})}
 const roomData=draft.rooms.find(r=>r.id===room);const fontOptions=Object.keys(fonts).map(k=>[k,{sans:'Arial',serif:'Georgia',modern:'Verdana',humanist:'Trebuchet',mono:'Courier',system:'Sistem yazısı'}[k]!] as [string,string]);
 return <Sheet open={open} onOpenChange={setOpen}><SheetContent className="design-panel"><SheetTitle>{roomData?`${roomData.title} · Odayı düzenle`:'Ana sayfayı düzenle'}</SheetTitle><SheetDescription>Değişiklikler önce sana görünür. Kaydettiğinde ziyaretçilere uygulanır.</SheetDescription><Tabs defaultValue="page"><TabsList className="panel-tabs"><TabsTrigger value="page">Sayfa</TabsTrigger><TabsTrigger value="objects">Nesneler</TabsTrigger><TabsTrigger value="texts">Metinler</TabsTrigger><TabsTrigger value="effects">Efektler</TabsTrigger></TabsList>
 <TabsContent value="page"><h3>Renkler ve arka plan</h3><div className="panel-colors">{[['background','Arka plan'],['surface','Kartlar'],['accent','Vurgu'],['text','Metin'],['muted','İkincil metin'],['border','Kenarlık'],['championColor','Şampiyon rengi']].map(([k,l])=><label key={k}>{l}<input type="color" value={(page as unknown as Record<string,string>)[k]??(draft as unknown as Record<string,string>)[k]??'#ffffff'} onChange={e=>update(k,e.target.value)}/></label>)}</div><label>Arka plan görseli<input type="url" value={page.backgroundImage??draft.backgroundImage} placeholder="https://…" onChange={e=>update('backgroundImage',e.target.value)}/></label><Range label="Arka plan karartma" value={page.backgroundOpacity} min={0} max={1} step={.05} onChange={v=>update('backgroundOpacity',v)}/><label>Yazı tipi<Choice value={page.font} options={fontOptions} onChange={v=>update('font',v)}/></label><Range label="Genel yazı boyutu (px)" value={page.fontSize??draft.fontSize} min={16} max={24} onChange={v=>update('fontSize',v)}/><h3>Yerleşim ve boyutlar</h3><Range label="Sayfa genişliği (px)" value={page.contentWidth} min={700} max={1800} step={20} onChange={v=>update('contentWidth',v)}/><Range label="Nesneler arası boşluk (px)" value={page.gap} min={8} max={80} onChange={v=>update('gap',v)}/><Range label="Bilgisayarda sütun sayısı" value={page.columns} min={1} max={5} onChange={v=>update('columns',v)}/><Range label="Telefonda sütun sayısı" value={page.mobileColumns} min={1} max={2} onChange={v=>update('mobileColumns',v)}/>{!room&&<><Range label="Futbol topu çapı (px)" value={page.ballSize} min={140} max={450} step={10} onChange={v=>update('ballSize',v)}/><label>Top görseli<input value={page.ballImage} onChange={e=>update('ballImage',e.target.value)}/></label><Range label="Top üzerindeki yazı zemini" value={page.ballShade} min={0} max={.9} step={.05} onChange={v=>update('ballShade',v)}/></>}{room&&<Range label="Şampiyon video genişliği (px)" value={page.championWidth} min={280} max={1000} step={10} onChange={v=>update('championWidth',v)}/>}</TabsContent>
 <TabsContent value="objects"><label>Düzenlenecek nesne<Choice value={element} options={Object.entries(elementMap).map(([k,v])=>[k,v[0]])} onChange={v=>setElement(v as ElementKey)}/></label><p className="panel-note">Boş bırakılan özellikler mevcut tasarımdan alınır. Boyutlar küçük ekranlarda sayfaya sığdırılır.</p><label>Yazı tipi<Choice value={object.font??page.font} options={fontOptions} onChange={v=>setObject('font',v)}/></label><div className="panel-colors">{[['color','Yazı'],['background','Zemin'],['borderColor','Kenarlık']].map(([k,l])=><label key={k}>{l}<input type="color" value={(object as Record<string,string>)[k]??(k==='color'?'#f3f6ea':k==='background'?'#102b22':'#365346')} onChange={e=>setObject(k,e.target.value)}/></label>)}</div>{([['fontSize','Yazı boyutu (px)',12,120,1,18],['weight','Yazı kalınlığı',100,900,100,400],['letterSpacing','Harf aralığı (px)',-2,12,.5,0],['lineHeight','Satır aralığı',1,2.5,.1,1.5],['width','Genişlik (px)',60,1500,10,280],['height','Yükseklik (px)',30,800,10,200],['padding','İç boşluk (px)',0,80,1,16],['margin','Dış boşluk (px)',0,80,1,0],['radius','Köşe yuvarlaklığı (px)',0,100,1,12],['borderWidth','Çerçeve kalınlığı (px)',0,12,1,1],['shadow','Gölge (px)',0,60,1,20],['opacity','Opaklık',.2,1,.05,1]] as const).map(([k,l,min,max,step,fallback])=><Range key={k} label={l} value={object[k]??fallback} min={min} max={max} step={step} onChange={v=>setObject(k,v)}/>)}<label>Hizalama<Choice value={object.align??'left'} options={[["left","Sol"],["center","Orta"],["right","Sağ"]]} onChange={v=>setObject('align',v)}/></label>{[['italic','İtalik'],['underline','Altı çizili'],['uppercase','Büyük harf'],['hidden','Nesneyi gizle']].map(([k,l])=><Toggle key={k} label={l} value={!!object[k as keyof ObjectAppearance]} onChange={v=>setObject(k,v)}/>)}<button className="panel-secondary" onClick={()=>{const next={...page.elements};delete next[element];setPage({...page,elements:next})}}>Bu nesnenin ayarlarını sıfırla</button></TabsContent>
 <TabsContent value="texts"><h3>{room?'Oda metinleri':'Site metinleri'}</h3>{roomData?<><label>Oda başlığı<input value={roomData.title} maxLength={80} onChange={e=>setDraft({...draft,rooms:draft.rooms.map(r=>r.id===room?{...r,title:e.target.value}:r)})}/></label><label>Oda açıklaması<textarea value={roomData.description} maxLength={180} onChange={e=>setDraft({...draft,rooms:draft.rooms.map(r=>r.id===room?{...r,description:e.target.value}:r)})}/></label></>:<>{([['name','Site adı'],['tagline','Üst etiket'],['title','Ana başlık'],['subtitle','Açıklama']] as const).map(([k,l])=><label key={k}>{l}<input value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}{draft.rooms.map(r=><fieldset key={r.id}><legend>{r.title}</legend><label>Top üzerindeki başlık<input value={r.title} maxLength={80} onChange={e=>setDraft({...draft,rooms:draft.rooms.map(x=>x.id===r.id?{...x,title:e.target.value}:x)})}/></label><label>Açıklama<textarea value={r.description} maxLength={180} onChange={e=>setDraft({...draft,rooms:draft.rooms.map(x=>x.id===r.id?{...x,description:e.target.value}:x)})}/></label><label>Top vurgu rengi<input type="color" value={r.accent} onChange={e=>setDraft({...draft,rooms:draft.rooms.map(x=>x.id===r.id?{...x,accent:e.target.value}:x)})}/></label></fieldset>)}</>}<h3>Etiketler ve düğmeler</h3>{Object.entries(labelDefaults).map(([key,value])=><label key={key}>{value}<textarea maxLength={500} value={page.labels[key]??value} onChange={e=>update('labels',{...page.labels,[key]:e.target.value})}/></label>)}</TabsContent>
 <TabsContent value="effects"><Toggle label="Hareket efektleri" value={page.motion??draft.motion} onChange={v=>update('motion',v)}/><Toggle label="Saha çizgileri" value={page.fieldLines??draft.fieldLines} onChange={v=>update('fieldLines',v)}/><Toggle label="Havai fişekler" value={page.fireworks} onChange={v=>update('fireworks',v)}/><Toggle label="Konfeti" value={page.confetti} onChange={v=>update('confetti',v)}/><Range label="Kutlama süresi (saniye)" value={page.celebrationDuration} min={3} max={15} step={.5} onChange={v=>update('celebrationDuration',v)}/><p className="panel-note">Kutlama, odada en az bir oy olduğunda çalışır. Cihazın azaltılmış hareket tercihi korunur.</p></TabsContent></Tabs>
 <div className="panel-actions"><span role="status">{dirty?'Kaydedilmemiş değişiklikler':'Tüm değişiklikler kaydedildi'}</span><button className="primary" disabled={busy||!dirty} onClick={save}>{busy?'Kaydediliyor…':'Değişiklikleri kaydet'}</button><div><button onClick={()=>setOpen(false)}>Sayfada önizle</button><button disabled={busy||!dirty} onClick={discard}>Vazgeç</button></div></div></SheetContent></Sheet>
}
